export const ASSET_LIST_REQUEST = 'ASSET_LIST_REQUEST';
export const ASSET_LIST_SUCCESS = 'ASSET_LIST_SUCCESS';
export const ASSET_LIST_FAIL = 'ASSET_LIST_FAIL';

export const ASSET_DETAILS_REQUEST = 'ASSET_DETAILS_REQUEST';
export const ASSET_DETAILS_SUCCESS = 'ASSET_DETAILS_SUCCESS';
export const ASSET_DETAILS_FAIL = 'ASSET_DETAILS_FAIL';

export const ASSET_DELETE_REQUEST = 'ASSET_DELETE_REQUEST';
export const ASSET_DELETE_SUCCESS = 'ASSET_DELETE_SUCCESS';
export const ASSET_DELETE_FAIL = 'ASSET_DELETE_FAIL';

export const ASSET_CREATE_REQUEST = 'ASSET_CREATE_REQUEST';
export const ASSET_CREATE_SUCCESS = 'ASSET_CREATE_SUCCESS';
export const ASSET_CREATE_FAIL = 'ASSET_CREATE_FAIL';
export const ASSET_CREATE_RESET = 'ASSET_CREATE_RESET';

export const ASSET_UPDATE_REQUEST = 'ASSET_UPDATE_REQUEST';
export const ASSET_UPDATE_SUCCESS = 'ASSET_UPDATE_SUCCESS';
export const ASSET_UPDATE_FAIL = 'ASSET_UPDATE_FAIL';
export const ASSET_UPDATE_RESET = 'ASSET_UPDATE_RESET';
