export const ASSET_LIST_REQUEST = 'ASSET_LIST_REQUEST';
export const ASSET_LIST_SUCCESS = 'ASSET_LIST_SUCCESS';
export const ASSET_LIST_FAIL = 'ASSET_LIST_FAIL';

export const ASSET_DETAILS_REQUEST = 'ASSET_DETAILS_REQUEST';
export const ASSET_DETAILS_SUCCESS = 'ASSET_DETAILS_SUCCESS';
export const ASSET_DETAILS_FAIL = 'ASSET_DETAILS_FAIL';
