export const REQUESTS_ADD_ITEM = 'REQUESTS_ADD_ITEM';
export const REQUESTS_REMOVE_ITEM = 'REQUESTS_REMOVE_ITEM';
export const REQUESTS_SHIPPING_ADDRESS = 'REQUESTS_SHIPPING_ADDRESS';
export const REQUESTS_PAYMENT_METHOD = 'REQUESTS_PAYMENT_METHOD';
